Viewset guidelines
C0D1UM/technical-standard pull request #10
Opened 2021-02-08 11:21 UTC by piyapan039285

2021-02-08 16:07 UTC, powerdefy requested changes
I think you dont need to disable the rule krub.

2021-02-08 16:07 UTC, powerdefy commented on django/readme/sample.md
> +* url: http://localhost:8000/
```suggestion
* url: `http://localhost:8000/`
```

You don't need to disable the rule krub.

2021-02-08 16:07 UTC, powerdefy commented on .markdownlint.yml
> +MD034: false
```suggestion
MD034: true
```
Per my below comment you don't need to disable this rule.

2021-02-09 02:59 UTC, earthpyy approved these changes
Cool krubb

2021-02-09 05:56 UTC, powerdefy approved these changes
Good krub

2021-02-09 05:56 UTC, merged